---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: update
    - role: prereq
    - role: download
    - role: raspberrypi
    - role: artis3n.tailscale

- hosts: master
  become: yes
  roles:
    - role: k3s/master

- hosts: node
  become: yes
  roles:
    - role: k3s/node
