kind: Deployment
apiVersion: apps/v1
metadata:
  name: discord-bot
  namespace: default
  labels:
    k8s-app: discord-bot
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: discord-bot
  template:
    metadata:
      name: discord-bot
      labels:
        k8s-app: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: autumnskerritt/ultimate-hacking-bot
          env:
            - name: token
              value: >-
                MzM0NzExNTYzMzI1ODAwNDU5.GNUocy.y30xmlVGEP63VdrZ3hlRhATQC1d2ShQUTa6EYE
          imagePullPolicy: Always
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 2
  updatedReplicas: 2
  unavailableReplicas: 2
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-11-28T09:15:38Z'
      lastTransitionTime: '2022-11-28T09:15:30Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "discord-bot-7678bb544" has successfully progressed.
    - type: Available
      status: 'False'
      lastUpdateTime: '2022-11-28T09:15:38Z'
      lastTransitionTime: '2022-11-28T09:15:38Z'
      reason: MinimumReplicasUnavailable
      message: Deployment does not have minimum availability.
